name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install xmllint
      run: sudo apt-get install -y openmpi-bin openmpi-doc libopenmpi-dev
    - name: checkout repo
      uses: actions/checkout@v2
    - name: build application
      run: make
